# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      -X github.com/takaishi/csv2tbl/cmd.version={{.Version}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: takaishi
      name: homebrew-fomulas
      branch: master
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "`csv2tbl` is tool to convert csv to table."
    homepage: "https://github.com/takaishi/csv2tbl"
    install: |
      bin.install Dir['csv2tbl']
    test: |
      system "#{bin}/csv2tbl"
